version: '3.8'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: championsclub123
      POSTGRES_DB: postgres
    networks:
      senpaislist-network:
          aliases:
              - postgres
    ports: 
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:5.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    networks:
      senpaislist-network:
          aliases:
              - pgadmin
    links:
    - "postgres:pgsql-server"
  backend:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - "./:/app"
    networks:
      senpaislist-network:
          aliases:
              - backend
    depends_on:
      - postgres
  # scripts:
  #   build: ./scripts/
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #   - "postgres"

volumes:
  db_data:
  pgadmin-data:

networks:
  senpaislist-network:
    external: true
