version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: championsclub123
      POSTGRES_DB: postgres
    networks:
      senpaislist-network:
          aliases:
              - postgres
    ports: 
      - 5432:5432

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:championsclub123@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      senpaislist-network:
          aliases:
              - graphql

  backend:
    build: .
    ports:
      - "5000:5000"
    networks:
      senpaislist-network:
          aliases:
              - backend
  scripts:
    build: ./scripts/
    ports:
      - "5001:5001"
    depends_on:
    - "postgres"

volumes:
  db_data:

networks:
  senpaislist-network:
    external: true
