// Code generated by sqlc. DO NOT EDIT.
// source: anime.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createAnime = `-- name: CreateAnime :one
INSERT INTO anime (
    title,
    title_jp,
    show_type,
    source, 
    begin_date,
    end_date,
    genre,
    season,
    year,
    airing,
    current_status,
    num_episodes,
    episode_duration,
    broadcast_time,
    next_broadcast,
    score,
    scored_by,
    rank,
    popularity,
    favorites,
    image_url
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21
) RETURNING title, title_jp, show_type, source, begin_date, end_date, genre, season, year, airing, current_status, num_episodes, episode_duration, broadcast_time, next_broadcast, score, scored_by, rank, popularity, favorites, image_url, id, created_at
`

type CreateAnimeParams struct {
	Title           string         `json:"title"`
	TitleJp         string         `json:"title_jp"`
	ShowType        string         `json:"show_type"`
	Source          string         `json:"source"`
	BeginDate       string         `json:"begin_date"`
	EndDate         sql.NullString `json:"end_date"`
	Genre           []string       `json:"genre"`
	Season          string         `json:"season"`
	Year            int64          `json:"year"`
	Airing          bool           `json:"airing"`
	CurrentStatus   string         `json:"current_status"`
	NumEpisodes     int64          `json:"num_episodes"`
	EpisodeDuration string         `json:"episode_duration"`
	BroadcastTime   string         `json:"broadcast_time"`
	NextBroadcast   sql.NullString `json:"next_broadcast"`
	Score           float64        `json:"score"`
	ScoredBy        int64          `json:"scored_by"`
	Rank            int64          `json:"rank"`
	Popularity      int64          `json:"popularity"`
	Favorites       int64          `json:"favorites"`
	ImageUrl        string         `json:"image_url"`
}

func (q *Queries) CreateAnime(ctx context.Context, arg CreateAnimeParams) (Anime, error) {
	row := q.db.QueryRowContext(ctx, createAnime,
		arg.Title,
		arg.TitleJp,
		arg.ShowType,
		arg.Source,
		arg.BeginDate,
		arg.EndDate,
		pq.Array(arg.Genre),
		arg.Season,
		arg.Year,
		arg.Airing,
		arg.CurrentStatus,
		arg.NumEpisodes,
		arg.EpisodeDuration,
		arg.BroadcastTime,
		arg.NextBroadcast,
		arg.Score,
		arg.ScoredBy,
		arg.Rank,
		arg.Popularity,
		arg.Favorites,
		arg.ImageUrl,
	)
	var i Anime
	err := row.Scan(
		&i.Title,
		&i.TitleJp,
		&i.ShowType,
		&i.Source,
		&i.BeginDate,
		&i.EndDate,
		pq.Array(&i.Genre),
		&i.Season,
		&i.Year,
		&i.Airing,
		&i.CurrentStatus,
		&i.NumEpisodes,
		&i.EpisodeDuration,
		&i.BroadcastTime,
		&i.NextBroadcast,
		&i.Score,
		&i.ScoredBy,
		&i.Rank,
		&i.Popularity,
		&i.Favorites,
		&i.ImageUrl,
		&i.ID,
		&i.CreatedAt,
	)
	return i, err
}
