package db

import (
	"database/sql"
	"log"
	"os"
	"testing"

	_ "github.com/lib/pq"
)

const (
	dbDriver = "postgres"
	dbSource = "postgresql://root:secret@localhost:5432/anime?sslmode=disable"
)

// Queriest object is defined in db.go
// generated by sqlc.
// contains a DBTX: can either be a db connection or a transaction
var testQueries *Queries

// build a db connection
func TestMain(m *testing.M) {
	// returns a connection object & err
	conn, err := sql.Open(dbDriver, dbSource)
	if err != nil {
		log.Fatal("cannot connect to db:", err)
	}

	// use the connection to create the new testQueries object
	// New() is defined in db.go
	testQueries = New(conn)

	os.Exit(m.Run())
}
