// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Anime struct {
	Title           sql.NullString  `json:"title"`
	TitleJp         sql.NullString  `json:"title_jp"`
	Type            sql.NullString  `json:"type"`
	Source          sql.NullString  `json:"source"`
	BeginDate       sql.NullString  `json:"begin_date"`
	EndDate         sql.NullString  `json:"end_date"`
	Genre           []string        `json:"genre"`
	Season          sql.NullString  `json:"season"`
	Year            sql.NullInt32   `json:"year"`
	Airing          sql.NullBool    `json:"airing"`
	CurrentStatus   sql.NullString  `json:"current_status"`
	NumEpisodes     sql.NullInt32   `json:"num_episodes"`
	EpisodeDuration sql.NullString  `json:"episode_duration"`
	BroadcastTime   sql.NullString  `json:"broadcast_time"`
	NextBroadcast   sql.NullString  `json:"next_broadcast"`
	Score           sql.NullFloat64 `json:"score"`
	ScoredBy        sql.NullInt32   `json:"scored_by"`
	Rank            sql.NullInt32   `json:"rank"`
	Popularity      sql.NullInt32   `json:"popularity"`
	Favorites       sql.NullInt32   `json:"favorites"`
	ImageUrl        sql.NullString  `json:"image_url"`
	ID              int64           `json:"id"`
	CreatedAt       time.Time       `json:"created_at"`
}
