// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Anime struct {
	Title           string    `json:"title"`
	TitleJp         string    `json:"title_jp"`
	StartDay        int64     `json:"start_day"`
	StartMonth      int64     `json:"start_month"`
	StartYear       int64     `json:"start_year"`
	EndDay          int64     `json:"end_day"`
	EndMonth        int64     `json:"end_month"`
	EndYear         int64     `json:"end_year"`
	Source          string    `json:"source"`
	Studio          string    `json:"studio"`
	Genres          []string  `json:"genres"`
	Rating          string    `json:"rating"`
	Description     string    `json:"description"`
	Season          string    `json:"season"`
	Year            string    `json:"year"`
	NumEpisodes     int64     `json:"num_episodes"`
	EpisodeDuration string    `json:"episode_duration"`
	Airing          bool      `json:"airing"`
	CurrentStatus   string    `json:"current_status"`
	NextBroadcast   string    `json:"next_broadcast"`
	Score           float64   `json:"score"`
	ScoredBy        int64     `json:"scored_by"`
	Rank            int64     `json:"rank"`
	Popularity      int64     `json:"popularity"`
	Favorites       int64     `json:"favorites"`
	ImageUrl        string    `json:"image_url"`
	ID              int64     `json:"id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Bookmark struct {
	Owner        string        `json:"owner"`
	AnimeID      sql.NullInt64 `json:"anime_id"`
	BookmarkType string        `json:"bookmark_type"`
	ID           int64         `json:"id"`
	CreatedAt    time.Time     `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
