// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Anime struct {
	ID        string     `json:"id"`
	Tid       int        `json:"tid"`
	Title     string     `json:"title"`
	TitleJp   string     `json:"title_jp"`
	Summary   string     `json:"summary"`
	Source    string     `json:"source"`
	Studio    string     `json:"studio"`
	ImageURL  string     `json:"imageUrl"`
	Statistic *Statistic `json:"statistic"`
}

type Statistic struct {
	AnimeID    string `json:"anime_id"`
	Score      int    `json:"score"`
	ScoredBy   int    `json:"scored_by"`
	Rank       int    `json:"rank"`
	Popularity int    `json:"popularity"`
	Favorites  int    `json:"favorites"`
	Rating     int    `json:"rating"`
}
