// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AiringInformation struct {
	AnimeID         string `json:"anime_id"`
	StartDay        int    `json:"start_day"`
	StartMonth      int    `json:"start_month"`
	StartYear       int    `json:"start_year"`
	Year            int    `json:"year"`
	Season          string `json:"season"`
	NumEpisodes     int    `json:"num_episodes"`
	EpisodeDuration int    `json:"episode_duration"`
	Airing          bool   `json:"airing"`
}

type Anime struct {
	ID                string             `json:"id"`
	Tid               int                `json:"tid"`
	Title             string             `json:"title"`
	TitleJp           string             `json:"title_jp"`
	Summary           string             `json:"summary"`
	Source            string             `json:"source"`
	Studio            string             `json:"studio"`
	ImageURL          string             `json:"imageUrl"`
	Statistic         *Statistic         `json:"statistic"`
	AiringInformation *AiringInformation `json:"airing_information"`
}

type Statistic struct {
	AnimeID    string `json:"anime_id"`
	Score      int    `json:"score"`
	ScoredBy   int    `json:"scored_by"`
	Rank       int    `json:"rank"`
	Popularity int    `json:"popularity"`
	Favorites  int    `json:"favorites"`
	Rating     int    `json:"rating"`
}
